version: "3.9"

services:
  cube:
    build:
      context: ./cube
      dockerfile: Dockerfile
    container_name: waggle-cube-1
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_API_SECRET=${CUBEJS_API_SECRET}
      - CUBEJS_DB_TYPE=bigquery
      - GOOGLE_APPLICATION_CREDENTIALS=/cube/creds/data-sandbox.json
    volumes:
      - ./cube:/cube
      - ./creds:/cube/creds:ro
    working_dir: /cube
    command: ["npx", "cubejs-server"]
    networks:
      - hivenet-secure

  mcp:
    build:
      context: ./mcp
      dockerfile: Dockerfile
    container_name: waggle-mcp-1
    restart: unless-stopped
    ports:
      - "3333:3333"
    environment:
      - CUBE_URL=http://cube:4000/cubejs-api/v1
      - CUBEJS_API_SECRET=${CUBEJS_API_SECRET}
      - PYTHONUNBUFFERED=1
    depends_on:
      - cube
    networks:
      - hivenet-secure

  nginx:
    image: nginx:alpine
    container_name: waggle-nginx-1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - cube
      - mcp
    networks:
      - hivenet-secure

networks:
  hivenet-secure:
    driver: bridge
